from .customer import *
from .address import *
from .category import *
from .diningtable import *
from .restaurantdescription import *
from .staff import *
from .menu import *
from .inventory import *
from .coupons import *
from .offers import *
from .base import *
from .booking import *
from .orders import *
from .order_items import *
from .bill import *
from .payment import *
from .review import *
from .customer_favourites import *
from .user_history import *
from .chatbot_conversation import *
