"""add chatbot sessions table

Revision ID: 5f0eede58ce3
Revises: 96fa5ad518d6
Create Date: 2026-07-20 19:30:28.182396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f0eede58ce3'
down_revision: Union[str, Sequence[str], None] = '96fa5ad518d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('current_intent', sa.String(length=50), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chatbot_sessions_session_id'), 'chatbot_sessions', ['session_id'], unique=False)
    op.alter_column('customers', 'total_members',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'total_members',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_chatbot_sessions_session_id'), table_name='chatbot_sessions')
    op.drop_table('chatbot_sessions')
    # ### end Alembic commands ###
