"""Initial schema

Revision ID: 96fa5ad518d6
Revises: 
Create Date: 2026-07-20 18:37:05.832839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fa5ad518d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_table('coupons',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('minimum_order_amount', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('coupon_id'),
    sa.UniqueConstraint('coupon_code')
    )
    op.create_index(op.f('ix_coupons_coupon_id'), 'coupons', ['coupon_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('favourite_cuisine', sa.String(length=200), nullable=True),
    sa.Column('spice_preference', sa.String(length=50), nullable=True),
    sa.Column('dietary_preference', sa.String(length=50), nullable=True),
    sa.Column('preferred_table_type', sa.String(length=30), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customers_telegram_id'), 'customers', ['telegram_id'], unique=True)
    op.create_table('diningtables',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=10), nullable=False),
    sa.Column('seating_capacity', sa.Integer(), nullable=False),
    sa.Column('table_type', sa.String(length=30), nullable=True),
    sa.Column('table_status', sa.String(length=30), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('table_id'),
    sa.UniqueConstraint('table_number')
    )
    op.create_index(op.f('ix_diningtables_table_id'), 'diningtables', ['table_id'], unique=False)
    op.create_table('restaurantdescriptions',
    sa.Column('restaurant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_address', sa.String(length=300), nullable=False),
    sa.Column('restaurant_landmark', sa.String(length=300), nullable=True),
    sa.Column('restaurant_capacity', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.Column('cuisine_type', sa.String(length=100), nullable=False),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('restaurant_status', sa.String(length=20), nullable=False),
    sa.Column('average_cost_for_two', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_restaurantdescriptions_restaurant_id'), 'restaurantdescriptions', ['restaurant_id'], unique=False)
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.String(length=300), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=300), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_addresses_address_id'), 'addresses', ['address_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('booking_status', sa.String(length=30), nullable=True),
    sa.Column('special_request', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('occassion', sa.Enum('Casual', 'Birthday', 'Anniversary'), nullable=True),
    sa.Column('booking_source', sa.Enum('Swiggy', 'Zomato'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['diningtables.table_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_bookings_booking_id'), 'bookings', ['booking_id'], unique=False)
    op.create_table('chatbot_conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(length=1000), nullable=False),
    sa.Column('bot_response', sa.String(length=2000), nullable=False),
    sa.Column('detected_intent', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Enum('User', 'Bot'), nullable=True),
    sa.Column('response_time_ms', sa.Time(), nullable=True),
    sa.Column('message_timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_chatbot_conversations_conversation_id'), 'chatbot_conversations', ['conversation_id'], unique=False)
    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_description_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_veg', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('preparation_time', sa.Time(), nullable=True),
    sa.Column('cuisine', sa.String(length=30), nullable=False),
    sa.Column('food_type', sa.String(length=50), nullable=False),
    sa.Column('spice_level', sa.String(length=30), nullable=True),
    sa.Column('serving_size', sa.String(length=30), nullable=True),
    sa.Column('allergens', sa.String(length=50), nullable=True),
    sa.Column('chefs_special', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['restaurant_description_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menu_menu_id'), 'menu', ['menu_id'], unique=False)
    op.create_table('offers',
    sa.Column('offer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('offer_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('discount_type', sa.Enum('Percentage', 'Flat'), nullable=True),
    sa.Column('minimum_order', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_index(op.f('ix_offers_offer_id'), 'offers', ['offer_id'], unique=False)
    op.create_table('staffs',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=30), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('resigning_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staffs_staff_id'), 'staffs', ['staff_id'], unique=False)
    op.create_table('user_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_user_history_history_id'), 'user_history', ['history_id'], unique=False)
    op.create_table('customer_favourites',
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ),
    sa.PrimaryKeyConstraint('favourite_id')
    )
    op.create_index(op.f('ix_customer_favourites_favourite_id'), 'customer_favourites', ['favourite_id'], unique=False)
    op.create_table('inventorys',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('stock_status', sa.String(length=30), nullable=True),
    sa.Column('reorder_level', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('supplier', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventorys_inventory_id'), 'inventorys', ['inventory_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('restaurant_description_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=30), nullable=True),
    sa.Column('order_status', sa.String(length=30), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_instruction', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.coupon_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['restaurant_description_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_table('bills',
    sa.Column('bill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bill_status', sa.String(length=30), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('service_charges', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Enum('Dine in', 'Dilevery', 'Take Away'), nullable=True),
    sa.Column('order_status', sa.Enum('Pending', 'Preparing', 'Ready', 'Delivered', 'Cancelled'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['diningtables.table_id'], ),
    sa.PrimaryKeyConstraint('bill_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_bills_bill_id'), 'bills', ['bill_id'], unique=False)
    op.create_table('orderitems',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('item_status', sa.Enum('Pending', 'Preparing', 'Ready', 'Served', 'Cancelled'), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_orderitems_order_item_id'), 'orderitems', ['order_item_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(length=500), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurantdescriptions.restaurant_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_review_id'), 'reviews', ['review_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.bill_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('bill_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_reviews_review_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_orderitems_order_item_id'), table_name='orderitems')
    op.drop_table('orderitems')
    op.drop_index(op.f('ix_bills_bill_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_inventorys_inventory_id'), table_name='inventorys')
    op.drop_table('inventorys')
    op.drop_index(op.f('ix_customer_favourites_favourite_id'), table_name='customer_favourites')
    op.drop_table('customer_favourites')
    op.drop_index(op.f('ix_user_history_history_id'), table_name='user_history')
    op.drop_table('user_history')
    op.drop_index(op.f('ix_staffs_staff_id'), table_name='staffs')
    op.drop_table('staffs')
    op.drop_index(op.f('ix_offers_offer_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_menu_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_chatbot_conversations_conversation_id'), table_name='chatbot_conversations')
    op.drop_table('chatbot_conversations')
    op.drop_index(op.f('ix_bookings_booking_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_addresses_address_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_restaurantdescriptions_restaurant_id'), table_name='restaurantdescriptions')
    op.drop_table('restaurantdescriptions')
    op.drop_index(op.f('ix_diningtables_table_id'), table_name='diningtables')
    op.drop_table('diningtables')
    op.drop_index(op.f('ix_customers_telegram_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_coupons_coupon_id'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
