from .address import Address
from .customer import Customer
from .category import Category
from .dining_table import Diningtable
from .restaurant_description import Restaurant_Description
from .inventory import Inventory
from .menu import Menu
from .orders import Order
from .order_item import OrderItem
from .user_history import UserHistory
from .offer import Offer
from .coupons import Coupon
from .chatbot_conversation import ChatBotConversation
from .payment import Payment
from .bill import Bill
from .review import Review
from .customer_favourites import CustomerFavourite
from .staff import Staff
from .booking import Booking
from .chatbot_session import ChatBotSession
